"""Automated API endpoint discovery from captured network traffic.

Analyses the request/response pairs collected by ``NetworkInterceptor``
to:

  1. Identify API endpoints (REST, GraphQL, etc.).
  2. Detect authentication mechanisms (Bearer, API-key, cookie-based).
  3. Normalise paths (replace UUID / numeric IDs with ``{id}``).
  4. Generate an OpenAPI 3.0 stub from the discovered surface.

Usage::

    from specter.network.interceptor import NetworkInterceptor
    from specter.network.api_discovery import APIDiscovery

    interceptor = NetworkInterceptor(session)
    await interceptor.enable()
    # ... browse the target ...
    await interceptor.disable()

    discovery = APIDiscovery(interceptor.captured)
    endpoints = discovery.discover()
    openapi   = discovery.to_openapi(title="Target API")
"""

from __future__ import annotations

import json
import logging
import re
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlparse, parse_qs

from specter.core.types import Request, Response

logger = logging.getLogger(__name__)

# ── regex helpers ─────────────────────────────────────────────────

# Matches UUIDs (v4) and numeric IDs common in REST URLs.
_UUID_RE = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
_NUMERIC_ID_RE = re.compile(r"(?<=/)\d{2,}(?=/|$)")
_HEX_ID_RE = re.compile(r"(?<=/)[0-9a-fA-F]{16,}(?=/|$)")

# Content types that indicate API responses.
_API_CONTENT_TYPES = {"application/json", "application/xml", "text/xml",
                      "application/graphql-response+json", "application/problem+json"}

# Static resource extensions to ignore.
_STATIC_EXT = {".js", ".css", ".png", ".jpg", ".jpeg", ".gif", ".svg",
               ".woff", ".woff2", ".ttf", ".eot", ".ico", ".map",
               ".webp", ".avif", ".mp4", ".webm"}


# ── data models ───────────────────────────────────────────────────

@dataclass
class AuthInfo:
    """Detected authentication mechanism."""
    kind: str       # "bearer", "api_key_header", "api_key_query", "cookie", "basic", "none"
    location: str   # header name, query param name, or cookie name
    sample: str     # redacted sample value

    def to_openapi_security(self) -> dict[str, Any]:
        """Produce an OpenAPI securityScheme fragment."""
        if self.kind == "bearer":
            return {"type": "http", "scheme": "bearer"}
        if self.kind == "basic":
            return {"type": "http", "scheme": "basic"}
        if self.kind == "api_key_header":
            return {"type": "apiKey", "in": "header", "name": self.location}
        if self.kind == "api_key_query":
            return {"type": "apiKey", "in": "query", "name": self.location}
        if self.kind == "cookie":
            return {"type": "apiKey", "in": "cookie", "name": self.location}
        return {}


@dataclass
class DiscoveredEndpoint:
    """A single API endpoint distilled from observed traffic."""
    method: str                                 # HTTP method
    path_template: str                          # e.g. /api/users/{id}
    base_url: str                               # scheme + host
    content_type: str = ""
    status_codes: list[int] = field(default_factory=list)
    query_params: list[str] = field(default_factory=list)
    auth: AuthInfo | None = None
    sample_request_headers: dict[str, str] = field(default_factory=dict)
    sample_response_headers: dict[str, str] = field(default_factory=dict)
    seen_count: int = 1
    has_body: bool = False

    @property
    def full_url(self) -> str:
        return f"{self.base_url}{self.path_template}"


# ── discovery engine ──────────────────────────────────────────────

class APIDiscovery:
    """Analyse captured traffic and auto-discover API endpoints.

    Parameters
    ----------
    traffic:
        List of ``(Request, Response | None)`` tuples, typically from
        ``NetworkInterceptor.captured``.
    """

    def __init__(self, traffic: list[tuple[Request, Response | None]]):
        self._traffic = traffic
        self._endpoints: list[DiscoveredEndpoint] = []

    # ── public API ────────────────────────────────────────────────

    def discover(self) -> list[DiscoveredEndpoint]:
        """Run the discovery pipeline and return deduplicated endpoints."""
        raw = self._extract_candidates()
        self._endpoints = self._deduplicate(raw)
        logger.info("Discovered %d API endpoints from %d requests",
                     len(self._endpoints), len(self._traffic))
        return list(self._endpoints)

    def to_openapi(
        self,
        *,
        title: str = "Discovered API",
        version: str = "0.1.0",
        description: str = "Auto-generated by Specter API Discovery",
    ) -> dict[str, Any]:
        """Generate an OpenAPI 3.0 stub from discovered endpoints.

        Returns a Python dict that can be serialised to JSON or YAML.
        """
        if not self._endpoints:
            self.discover()

        paths: dict[str, dict[str, Any]] = {}
        security_schemes: dict[str, Any] = {}
        servers: set[str] = set()

        for ep in self._endpoints:
            servers.add(ep.base_url)
            path = ep.path_template
            if path not in paths:
                paths[path] = {}

            operation: dict[str, Any] = {
                "summary": f"{ep.method} {path}",
                "responses": {},
            }

            # Query params
            if ep.query_params:
                operation["parameters"] = [
                    {"name": qp, "in": "query", "schema": {"type": "string"}}
                    for qp in ep.query_params
                ]

            # Status codes
            for code in sorted(set(ep.status_codes)):
                operation["responses"][str(code)] = {
                    "description": _status_text(code),
                }
                if ep.content_type:
                    operation["responses"][str(code)]["content"] = {
                        ep.content_type: {"schema": {"type": "object"}}
                    }
            if not operation["responses"]:
                operation["responses"]["200"] = {"description": "OK"}

            # Request body hint
            if ep.has_body and ep.method in ("POST", "PUT", "PATCH"):
                ct = ep.sample_request_headers.get("content-type",
                      ep.sample_request_headers.get("Content-Type", "application/json"))
                operation["requestBody"] = {
                    "content": {ct: {"schema": {"type": "object"}}},
                }

            # Auth
            if ep.auth and ep.auth.kind != "none":
                scheme_name = f"{ep.auth.kind}_auth"
                security_schemes[scheme_name] = ep.auth.to_openapi_security()
                operation["security"] = [{scheme_name: []}]

            paths[path][ep.method.lower()] = operation

        spec: dict[str, Any] = {
            "openapi": "3.0.3",
            "info": {"title": title, "version": version, "description": description},
            "servers": [{"url": s} for s in sorted(servers)],
            "paths": paths,
        }
        if security_schemes:
            spec["components"] = {"securitySchemes": security_schemes}

        return spec

    def to_openapi_json(self, **kw: Any) -> str:
        """Convenience: return the OpenAPI stub as a JSON string."""
        return json.dumps(self.to_openapi(**kw), indent=2)

    # ── internals ─────────────────────────────────────────────────

    def _extract_candidates(self) -> list[DiscoveredEndpoint]:
        """First pass: filter traffic to probable API calls."""
        candidates: list[DiscoveredEndpoint] = []
        for req, resp in self._traffic:
            if not self._is_api_candidate(req, resp):
                continue

            parsed = urlparse(req.url)
            base = f"{parsed.scheme}://{parsed.netloc}"
            path = self._normalise_path(parsed.path)
            qp = list(parse_qs(parsed.query).keys())
            auth = self._detect_auth(req)

            ep = DiscoveredEndpoint(
                method=req.method,
                path_template=path,
                base_url=base,
                content_type=resp.mime_type if resp else "",
                status_codes=[resp.status] if resp else [],
                query_params=qp,
                auth=auth,
                sample_request_headers=dict(req.headers),
                sample_response_headers=dict(resp.headers) if resp else {},
                has_body=bool(req.post_data),
            )
            candidates.append(ep)
        return candidates

    def _deduplicate(
        self, endpoints: list[DiscoveredEndpoint]
    ) -> list[DiscoveredEndpoint]:
        """Merge endpoints that share (method, path_template, base_url)."""
        key_map: dict[tuple[str, str, str], DiscoveredEndpoint] = {}
        for ep in endpoints:
            key = (ep.method, ep.path_template, ep.base_url)
            if key in key_map:
                existing = key_map[key]
                existing.seen_count += 1
                for sc in ep.status_codes:
                    if sc not in existing.status_codes:
                        existing.status_codes.append(sc)
                for qp in ep.query_params:
                    if qp not in existing.query_params:
                        existing.query_params.append(qp)
                if ep.has_body:
                    existing.has_body = True
            else:
                key_map[key] = ep
        return list(key_map.values())

    # ── heuristics ────────────────────────────────────────────────

    @staticmethod
    def _is_api_candidate(req: Request, resp: Response | None) -> bool:
        """Decide whether a request looks like an API call."""
        parsed = urlparse(req.url)
        path = parsed.path.lower()

        # Skip static assets.
        for ext in _STATIC_EXT:
            if path.endswith(ext):
                return False

        # XHR / Fetch resource types are strong signals.
        if req.resource_type in ("XHR", "Fetch"):
            return True

        # Content-type check on response.
        if resp and resp.mime_type:
            base_ct = resp.mime_type.split(";")[0].strip().lower()
            if base_ct in _API_CONTENT_TYPES:
                return True

        # Path heuristics.
        api_indicators = ("/api/", "/api.", "/graphql", "/rest/",
                          "/v1/", "/v2/", "/v3/", "/v4/")
        if any(indicator in path for indicator in api_indicators):
            return True

        # POST with JSON body
        if req.method == "POST" and req.post_data:
            ct = req.headers.get("Content-Type", req.headers.get("content-type", ""))
            if "json" in ct:
                return True

        return False

    @staticmethod
    def _normalise_path(path: str) -> str:
        """Replace UUIDs and numeric IDs in a URL path with ``{id}``."""
        normalised = _UUID_RE.sub("{id}", path)
        normalised = _HEX_ID_RE.sub("{id}", normalised)
        normalised = _NUMERIC_ID_RE.sub("{id}", normalised)
        # Collapse consecutive {id}s.
        normalised = re.sub(r"(\{id\}/)+\{id\}", "{id}", normalised)
        return normalised or "/"

    @staticmethod
    def _detect_auth(req: Request) -> AuthInfo:
        """Inspect request headers for authentication tokens."""
        auth_header = req.headers.get("Authorization", req.headers.get("authorization", ""))
        if auth_header:
            lower = auth_header.lower()
            if lower.startswith("bearer "):
                token = auth_header[7:]
                return AuthInfo("bearer", "Authorization", _redact(token))
            if lower.startswith("basic "):
                return AuthInfo("basic", "Authorization", "***")
            # Might be a raw API key in the Authorization header.
            return AuthInfo("api_key_header", "Authorization", _redact(auth_header))

        # Common API-key header names.
        api_key_headers = ("x-api-key", "api-key", "apikey", "x-auth-token",
                           "x-access-token", "x-token")
        for hdr_name in api_key_headers:
            for actual_name, val in req.headers.items():
                if actual_name.lower() == hdr_name and val:
                    return AuthInfo("api_key_header", actual_name, _redact(val))

        # Cookie-based auth detection (common session cookie names).
        cookie = req.headers.get("Cookie", req.headers.get("cookie", ""))
        if cookie:
            session_names = ("session", "sid", "sess", "token", "jwt",
                             "auth", "connect.sid", "JSESSIONID", "PHPSESSID",
                             "_session_id")
            for part in cookie.split(";"):
                part = part.strip()
                if "=" in part:
                    name = part.split("=", 1)[0].strip()
                    if any(sn.lower() in name.lower() for sn in session_names):
                        return AuthInfo("cookie", name, "***")

        return AuthInfo("none", "", "")


# ── helpers ───────────────────────────────────────────────────────

def _redact(value: str, keep: int = 6) -> str:
    """Show the first ``keep`` chars and mask the rest."""
    if len(value) <= keep:
        return "***"
    return value[:keep] + "***"


def _status_text(code: int) -> str:
    """Return a short description for common HTTP status codes."""
    texts = {
        200: "OK", 201: "Created", 204: "No Content",
        301: "Moved Permanently", 302: "Found", 304: "Not Modified",
        400: "Bad Request", 401: "Unauthorized", 403: "Forbidden",
        404: "Not Found", 405: "Method Not Allowed",
        409: "Conflict", 422: "Unprocessable Entity", 429: "Too Many Requests",
        500: "Internal Server Error", 502: "Bad Gateway", 503: "Service Unavailable",
    }
    return texts.get(code, f"HTTP {code}")
